name = "task_coroutines"
description = "Coroutines and generators using only standard tasking features"
version = "0.1.0-dev"
licenses = "MIT"
tags = ["coroutine", "generator"]
website = "https://github.com/Fabien-Chouteau/task_coroutines"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
