on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  main:
    strategy:

      fail-fast: false # Don't stop all the workflows when one of them fails.

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # List of GitHuh Actions platform to run the workflow on

    runs-on: ${{ matrix.os }} # Run the continous integration workflow on each OS listed in the matrix.

    steps:
        # Check-out the repository
      - uses: actions/checkout@v3
        with:
          submodules: recursive

        # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1

        # Build the project using the validation build profile to enforce static analysis and coding style.
      - run: alr -v build --validation

        # Run the testsuite
      - run: cd tests && alr -v build
      - run: cd tests && alr -q run
